global_frame: base_frame
robot_base_frame: base_frame
rolling_window: false
width: 4.0
height: 4.0
origin_x: -2.0
origin_y: -2.0
resolution : 0.07
inflation_radius : 0.2
plugins:
  - {name: obstacles_laser,           type: "costmap_2d::ObstacleLayer"}
  - {name: inflation,                 type: "costmap_2d::InflationLayer"}
