footprint: [[-0.22, -0.22], [-0.22, 0.22], [0.22, 0.22], [0.22, -0.22]]
#[-0.5, -0.33], [-0.5, 0.33], [0.5, 0.33], [0.5, -0.33]
footprint_padding: 0.025

robot_base_frame: base_frame
update_frequency: 6.0
publish_frequency: 6.0
transform_tolerance: 0.5

resolution: 0.5 #0.025

obstacle_range: 1.5
raytrace_range: 6.0

#layer definitions
static:
    map_topic: /map
    subscribe_to_updates: true

obstacles_laser:
    observation_sources: laser
    laser: {data_type: LaserScan, clearing: true, marking: true, topic: scan, inf_is_valid: true}

inflation:
    inflation_radius: 0.1
    cost_scaling_factor: 5


#always_send_full_costmap : true
