global_frame: base_frame
robot_base_frame: base_frame
rolling_window: false
track_unknown_space: true

width: 1.0
height: 1.0
origin_x: -0.50
origin_y: -0.50

plugins:
  - {name: obstacles_laser,           type: "costmap_2d::ObstacleLayer"}
  - {name: inflation,                 type: "costmap_2d::InflationLayer"}
