footprint: [[-0.12, -0.13], [-0.12, 0.13], [0.25, 0.13], [0.25, -0.13]]
footprint_padding: 0.08

robot_base_frame: base_frame
update_frequency: 2.0
publish_frequency: 2.0
transform_tolerance: 0.5

resolution: 0.025

obstacle_range: 3.0
raytrace_range: 6.0

#layer definitions
static:
    map_topic: /map
    subscribe_to_updates: true

obstacles_laser:
    observation_sources: laser
    laser: {data_type: LaserScan, clearing: true, marking: true, topic: scan, inf_is_valid: true}

inflation:
    inflation_radius: 0.36
    cost_scaling_factor: 1.0
