global_frame: base_frame
robot_base_frame: base_frame
rolling_window: true
width: 2.0
height: 2.0
origin_x: -1.0
origin_y: -1.0

plugins:
  - {name: obstacles_laser,           type: "costmap_2d::ObstacleLayer"}
  - {name: inflation,                 type: "costmap_2d::InflationLayer"}
