footprint: [[-0.36, -0.29], [-0.36, 0.31], [0.2, 0.31], [0.2, -0.29]]
footprint_padding: 0.01

robot_base_frame: base_frame
update_frequency: 5
publish_frequency: 5
transform_tolerance: 0.8

resolution: 0.05

obstacle_range: 2.0
raytrace_range: 10.0

#layer definitions
static:
    map_topic: /map
    subscribe_to_updates: true

obstacles_laser:
    observation_sources: laser
    laser: {data_type: LaserScan, clearing: true, marking: true, topic: scan, inf_is_valid: true}

inflation:
    inflation_radius: 0.7
    cost_scaling_factor: 1.30
